name: Download from Localazy

on: 
  push:
    tags:
    - 'v*'

jobs:
  localazy-download:
    name: Download strings from Localazy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - run: ls src/locales/**/*.json

      - uses: actions/upload-artifact@v4
        with:
          name: localazy-files
          path: src/locales/**/*.json
